# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aef0e6d23260a2bfd2b0cfb941f45c2dbd2e82f3573e0848f48f7a28c5f93c7b46a0e07c63ee45f58fbb8612479e854372aa4ba3a00b6d1e92fb22097a9b503

test:
  secret_key_base: 025e165accd2e13fa81b210b2765d830a7e1850dc9ee7694c71e35d4b6d8a1dd782bc2b90f9a399ba1ce0099514e2c55b8b89cfc1c742ad85c123e62a63caf47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
